name: otomadb-images
version: "3.9"

services:
  redis:
    image: redis:7.0
    ports:
      - target: 6379
        published: 16379

  imgproxy:
    image: darthsim/imgproxy:latest
    ports:
      - target: 8080
        published: 18080
    environment:
      IMGPROXY_KEY: $IMGPROXY_KEY
      IMGPROXY_SALT: $IMGPROXY_SALT
